name: Release

on:
  push:
    branches:
      - main  # Run this action on every push to the main branch.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Generate changelog
      run: npm run changelog

    - name: Commit and push changelog
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add CHANGELOG.md
        git commit -m "Update changelog"
        git push

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
      with:
        tag_name: "v${{ github.sha }}"  # Use commit SHA for versioning or customize as needed
        release_name: "Release ${{ github.sha }}"
        body_path: "./CHANGELOG.md"     # Use the generated changelog as the release body
        draft: false
        prerelease: false




















 

