name-template: 'Release $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE (#$NUMBER)'
categories:
  - title: '🚀 Features'
    labels: ['feature']
  - title: '🐛 Bug Fixes'
    labels: ['bug']
  - title: '📚 Documentation'
    labels: ['documentation']
  - title: '🎨 Chore'
    labels: ['chore']
