# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on: 
  push:
    branches:
      - main
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
env:

  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Ubuntu:
    # The type of runner that the job will run on
    permissions:
        # write permission is required to create a github release
        contents: write
        # write permission is required for autolabeler
        # otherwise, read permission is required at least
        pull-requests: write
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
   
      - name: Get current date
        if: "contains(github.event.head_commit.message, 'Release')"
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

      - name: Add ChangeLog
        if: "contains(github.event.head_commit.message, 'Release')"
        uses: release-drafter/release-drafter@v5
        id: create_release
        with:
          tag: ${{ steps.date.outputs.date }}
          name: ""
          version: ${{ github.event.head_commit.message }}
          prerelease: false
          publish: true
